version: '3.8'

services:
  nginx-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    container_name: my-nginx-learning
